# Form implementation generated from reading ui file 'Заочка.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(849, 414)
        self.asc1 = QtWidgets.QRadioButton(Dialog)
        self.asc1.setGeometry(QtCore.QRect(30, 140, 611, 51))
        self.asc1.setObjectName("asc1")
        self.asc2 = QtWidgets.QRadioButton(Dialog)
        self.asc2.setEnabled(True)
        self.asc2.setGeometry(QtCore.QRect(30, 210, 641, 41))
        self.asc2.setObjectName("asc2")
        self.asc3 = QtWidgets.QRadioButton(Dialog)
        self.asc3.setGeometry(QtCore.QRect(30, 270, 631, 41))
        self.asc3.setCheckable(True)
        self.asc3.setChecked(False)
        self.asc3.setObjectName("asc3")
        self.next = QtWidgets.QPushButton(Dialog)
        self.next.setGeometry(QtCore.QRect(20, 320, 121, 61))
        self.next.setStyleSheet("border-radius:20%;\n"
"background:LightGray;")
        self.next.setObjectName("next")
        self.rezult = QtWidgets.QPushButton(Dialog)
        self.rezult.setGeometry(QtCore.QRect(160, 320, 121, 61))
        self.rezult.setStyleSheet("border-radius:20%;\n"
"background:LightGray;")
        self.rezult.setObjectName("rezult")
        self.number = QtWidgets.QLabel(Dialog)
        self.number.setGeometry(QtCore.QRect(20, 380, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.number.setFont(font)
        self.number.setObjectName("number")
        self.picture = QtWidgets.QLabel(Dialog)
        self.picture.setGeometry(QtCore.QRect(620, 130, 221, 261))
        self.picture.setText("")
        self.picture.setObjectName("picture")
        self.vopros = QtWidgets.QTextEdit(Dialog)
        self.vopros.setGeometry(QtCore.QRect(20, 10, 791, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vopros.setFont(font)
        self.vopros.setStyleSheet("border-radius:20%;\n"
"background:LightGray;\n"
"")
        self.vopros.setReadOnly(True)
        self.vopros.setObjectName("vopros")
        self.rezult_2 = QtWidgets.QPushButton(Dialog)
        self.rezult_2.setEnabled(True)
        self.rezult_2.setGeometry(QtCore.QRect(300, 320, 121, 61))
        self.rezult_2.setStyleSheet("border-radius:20%;\n"
"background:LightGray;")
        self.rezult_2.setObjectName("rezult_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Тест по истории искусств"))
        self.asc1.setText(_translate("Dialog", "RadioButton"))
        self.asc2.setText(_translate("Dialog", "RadioButton"))
        self.asc3.setText(_translate("Dialog", "RadioButton"))
        self.next.setText(_translate("Dialog", "Следующий "))
        self.rezult.setText(_translate("Dialog", "Результат "))
        self.number.setText(_translate("Dialog", "TextLabel"))
        self.rezult_2.setText(_translate("Dialog", "Начать заново"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
