# Form implementation generated from reading ui file 'test_form.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(647, 677)
        Dialog.setMinimumSize(QtCore.QSize(580, 70))
        Dialog.setStyleSheet("background: rgb(199, 199, 148);")
        self.next = QtWidgets.QPushButton(parent=Dialog)
        self.next.setGeometry(QtCore.QRect(50, 510, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        font.setBold(False)
        self.next.setFont(font)
        self.next.setStyleSheet("border-radius:20px;\n"
"background:rgb(170, 170, 127);\n"
"")
        self.next.setObjectName("next")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 170, 580, 321))
        self.widget.setMaximumSize(QtCore.QSize(580, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.question = QtWidgets.QTextEdit(parent=self.widget)
        self.question.setMinimumSize(QtCore.QSize(580, 70))
        self.question.setMaximumSize(QtCore.QSize(580, 100))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(14)
        self.question.setFont(font)
        self.question.setStyleSheet("border-radius:20px;\n"
"background:rgb(170, 170, 127);\n"
"")
        self.question.setReadOnly(True)
        self.question.setObjectName("question")
        self.verticalLayout.addWidget(self.question)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.response_1 = QtWidgets.QRadioButton(parent=self.widget)
        self.response_1.setMinimumSize(QtCore.QSize(580, 40))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.response_1.setFont(font)
        self.response_1.setStyleSheet("border-radius:20px;\n"
"border-radius:10px;\n"
"background:rgb(150, 150, 112)\n"
"")
        self.response_1.setObjectName("response_1")
        self.verticalLayout.addWidget(self.response_1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.response_2 = QtWidgets.QRadioButton(parent=self.widget)
        self.response_2.setMinimumSize(QtCore.QSize(580, 40))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.response_2.setFont(font)
        self.response_2.setStyleSheet("border-radius:20px;\n"
"border-radius:10px;\n"
"background:rgb(150, 150, 112)\n"
"")
        self.response_2.setObjectName("response_2")
        self.verticalLayout.addWidget(self.response_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.response_3 = QtWidgets.QRadioButton(parent=self.widget)
        self.response_3.setMinimumSize(QtCore.QSize(580, 40))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.response_3.setFont(font)
        self.response_3.setStyleSheet("border-radius:20px;\n"
"border-radius:10px;\n"
"background:rgb(150, 150, 112)\n"
"")
        self.response_3.setObjectName("response_3")
        self.verticalLayout.addWidget(self.response_3)
        self.widget1 = QtWidgets.QWidget(parent=Dialog)
        self.widget1.setGeometry(QtCore.QRect(30, 40, 588, 32))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget1)
        self.label.setMinimumSize(QtCore.QSize(230, 30))
        self.label.setMaximumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.subject = QtWidgets.QComboBox(parent=self.widget1)
        self.subject.setMinimumSize(QtCore.QSize(350, 30))
        self.subject.setMaximumSize(QtCore.QSize(350, 30))
        self.subject.setStyleSheet("background-color:rgb(170, 170, 127);")
        self.subject.setObjectName("subject")
        self.horizontalLayout.addWidget(self.subject)
        self.widget2 = QtWidgets.QWidget(parent=Dialog)
        self.widget2.setGeometry(QtCore.QRect(30, 100, 588, 32))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget2)
        self.label_2.setMinimumSize(QtCore.QSize(100, 30))
        self.label_2.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.testName = QtWidgets.QComboBox(parent=self.widget2)
        self.testName.setMinimumSize(QtCore.QSize(480, 30))
        self.testName.setMaximumSize(QtCore.QSize(480, 30))
        self.testName.setStyleSheet("background-color:rgb(170, 170, 127);")
        self.testName.setObjectName("testName")
        self.horizontalLayout_2.addWidget(self.testName)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Тест по истории"))
        self.next.setText(_translate("Dialog", "Следующий"))
        self.response_1.setText(_translate("Dialog", "Radio Button"))
        self.response_2.setText(_translate("Dialog", "Radio Button"))
        self.response_3.setText(_translate("Dialog", "Radio Button"))
        self.label.setText(_translate("Dialog", "Предмет"))
        self.label_2.setText(_translate("Dialog", "Тема"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
